INSERT INTO [bronze_defeated_mps] ([ons_id],[constituency_name],[region_name],[country_name],[constituency_type],[result],[party_abbreviation],[party_name],[firstname],[surname],[middlenames],[mnis_id],[gender],[defeated_mp],[former_mp],[title])
VALUES
('S14000062','Aberdeenshire North and Moray East','Scotland','Scotland','County','SNP gain from Con','Con','Conservative','Douglas','Ross','Gordon','4627','Male','Yes','Yes',NULL),
('S14000063','Airdrie and Shotts','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Anum','Qaisar',NULL,'4917','Female','Yes','Yes',NULL),
('E14001063','Aldershot','South East','England','Borough','Lab gain from Con','Con','Conservative','Leo','Docherty',NULL,'4600','Male','Yes','Yes',NULL),
('S14000064','Alloa and Grangemouth','Scotland','Scotland','County','Lab gain from SNP','Alba','Alba Party','Kenny','MacAskill','Wright','4772','Male','Yes','Yes',NULL),
('S14000064','Alloa and Grangemouth','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','John','Nicolson','MacKenzie','4415','Male','Yes','Yes',NULL),
('E14001066','Amber Valley','East Midlands','England','County','Lab gain from Con','Con','Conservative','Nigel','Mills','John','4136','Male','Yes','Yes',NULL),
('E14001069','Ashford','South East','England','County','Lab gain from Con','Con','Conservative','Damian','Green','Howard','76','Male','Yes','Yes',NULL),
('E14001071','Aylesbury','South East','England','County','Lab gain from Con','Con','Conservative','Rob','Butler',NULL,'4745','Male','Yes','Yes',NULL),
('S14000107','Ayr, Carrick and Cumnock','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Allan','Dorans',NULL,'4740','Male','Yes','Yes',NULL),
('E14001072','Banbury','South East','England','County','Lab gain from Con','Con','Conservative','Victoria','Prentis',NULL,'4401','Female','Yes','Yes',NULL),
('W07000083','Bangor Aberconwy','Wales','Wales','County','Lab gain from Con','Con','Conservative','Robin','Millar',NULL,'4746','Male','Yes','Yes',NULL),
('E14001076','Barrow and Furness','North West','England','County','Lab gain from Con','Con','Conservative','Simon','Fell',NULL,'4744','Male','Yes','Yes','Mr'),
('E14001078','Basingstoke','South East','England','Borough','Lab gain from Con','Con','Conservative','Maria','Miller','Frances Lewis','1480','Female','Yes','Yes','Dame'),
('E14001079','Bassetlaw','East Midlands','England','County','Lab gain from Con','Con','Conservative','Brendan','Clarke-Smith',NULL,'4756','Male','Yes','Yes',NULL),
('S14000068','Bathgate and Linlithgow','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Martyn','Day',NULL,'4488','Male','Yes','Yes',NULL),
('E14001097','Birmingham Northfield','West Midlands','England','Borough','Lab gain from Con','Con','Conservative','Gary','Sambrook',NULL,'4760','Male','Yes','Yes',NULL),
('E14001098','Birmingham Perry Barr','West Midlands','England','Borough','Ind gain from Lab','Lab','Labour','Khalid','Mahmood',NULL,'1392','Male','Yes','Yes',NULL),
('E14001102','Blackburn','North West','England','Borough','Ind gain from Lab','Lab','Labour','Kate','Hollern',NULL,'4363','Female','Yes','Yes','Ms'),
('E14001104','Blackpool North and Fleetwood','North West','England','Borough','Lab gain from Con','Con','Conservative','Paul','Maynard','Christopher','3926','Male','Yes','Yes','Mr'),
('E14001109','Bolsover','East Midlands','England','County','Lab gain from Con','Con','Conservative','Mark','Fletcher','Peter','4774','Male','Yes','Yes',NULL),
('E14001112','Bolton West','North West','England','County','Lab gain from Con','Con','Conservative','Chris','Green',NULL,'4398','Male','Yes','Yes','Mr'),
('E14001114','Boston and Skegness','East Midlands','England','County','RUK gain from Con','Con','Conservative','Matt','Warman',NULL,'4361','Male','Yes','Yes',NULL),
('E14001115','Bournemouth East','South West','England','Borough','Lab gain from Con','Con','Conservative','Tobias','Ellwood',NULL,'1487','Male','Yes','Yes',NULL),
('E14001116','Bournemouth West','South West','England','Borough','Lab gain from Con','Con','Conservative','Conor','Burns',NULL,'3922','Male','Yes','Yes','Sir'),
('E14001117','Bracknell','South East','England','Borough','Lab gain from Con','Con','Conservative','James','Sunderland','De Ville','4767','Male','Yes','Yes',NULL),
('W07000085','Brecon, Radnor and Cwm Tawe','Wales','Wales','County','LD gain from Con','Con','Conservative','Fay','Jones',NULL,'4763','Female','Yes','Yes',NULL),
('E14001131','Bristol Central','South West','England','Borough','Green gain from Lab','Lab','Labour','Thangam','Debbonaire','Elizabeth Rachel','4433','Female','Yes','Yes',NULL),
('E14001140','Broxtowe','East Midlands','England','County','Lab gain from Con','Con','Conservative','Darren','Henry','George','4794','Male','Yes','Yes',NULL),
('E14001141','Buckingham and Bletchley','South East','England','County','Lab gain from Con','Con','Conservative','Iain','Stewart',NULL,'4015','Male','Yes','Yes',NULL),
('E14001142','Burnley','North West','England','County','Lab gain from Con','Con','Conservative','Antony','Higginbotham',NULL,'4833','Male','Yes','Yes','Mr'),
('E14001143','Burton and Uttoxeter','West Midlands','England','County','Lab gain from Con','Con','Conservative','Kate','Kniveton','Elizabeth','4773','Female','Yes','Yes',NULL),
('E14001144','Bury North','North West','England','Borough','Lab gain from Con','Con','Conservative','James','Daly','Barry','4854','Male','Yes','Yes',NULL),
('W07000087','Caerfyrddin','Wales','Wales','County','PC gain from Con','Con','Conservative','Simon','Hart','Anthony','3944','Male','Yes','Yes',NULL),
('E14001150','Cannock Chase','West Midlands','England','County','Lab gain from Con','Con','Conservative','Amanda','Milling','Anne','4454','Female','Yes','Yes',NULL),
('E14001152','Carlisle','North West','England','County','Lab gain from Con','Con','Conservative','John','Stevenson',NULL,'3942','Male','Yes','Yes','Mr'),
('E14001153','Carshalton and Wallington','London','England','Borough','LD gain from Con','Con','Conservative','Elliot','Colburn',NULL,'4775','Male','Yes','Yes',NULL),
('E14001158','Cheadle','North West','England','Borough','LD gain from Con','Con','Conservative','Mary','Robinson',NULL,'4406','Female','Yes','Yes','Ms'),
('E14001159','Chelmsford','East of England','England','Borough','LD gain from Con','Con','Conservative','Vicky','Ford',NULL,'4674','Female','Yes','Yes',NULL),
('E14001160','Chelsea and Fulham','London','England','Borough','Lab gain from Con','Con','Conservative','Greg','Hands','William','1526','Male','Yes','Yes',NULL),
('E14001161','Cheltenham','South West','England','Borough','LD gain from Con','Con','Conservative','Alex','Chalk',NULL,'4481','Male','Yes','Yes',NULL),
('E14001166','Chichester','South East','England','County','LD gain from Con','Con','Conservative','Gillian','Keegan',NULL,'4680','Female','Yes','Yes',NULL),
('E14001169','Chipping Barnet','London','England','Borough','Lab gain from Con','Con','Conservative','Theresa','Villiers','Anne','1500','Female','Yes','Yes',NULL),
('E14001174','Clacton','East of England','England','County','RUK gain from Con','Con','Conservative','Giles','Watling','Francis','4677','Male','Yes','Yes',NULL),
('W07000094','Clwyd East','Wales','Wales','County','Lab gain from Con','Con','Conservative','James ','Davies','Michael','4476','Male','Yes','Yes','Dr'),
('W07000094','Clwyd East','Wales','Wales','County','Lab gain from Con','Ind','Independent','Rob','Roberts','Joseph','4810','Male','Yes','Yes','Mr'),
('S14000070','Coatbridge and Bellshill','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Steven','Bonnar',NULL,'4748','Male','Yes','Yes',NULL),
('E14001177','Colne Valley','Yorkshire and The Humber','England','County','Lab gain from Con','Con','Conservative','Jason','McCartney','Alexander','3953','Male','Yes','Yes',NULL),
('E14001178','Congleton','North West','England','County','Lab gain from Con','Con','Conservative','Fiona','Bruce','Claire','3958','Female','Yes','Yes','Mrs'),
('E14001179','Corby and East Northamptonshire','East Midlands','England','County','Lab gain from Con','Con','Conservative','Tom','Pursglove',NULL,'4369','Male','Yes','Yes',NULL),
('S14000071','Cowdenbeath and Kirkcaldy','Scotland','Scotland','County','Lab gain from SNP','Alba','Alba Party','Neale','Hanvey',NULL,'4782','Male','Yes','Yes',NULL),
('E14001183','Cramlington and Killingworth','North East','England','County','Lab hold','Con','Conservative','Ian','Levy',NULL,'4749','Male','Yes','Yes',NULL),
('S14000072','Cumbernauld and Kirkintilloch','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Stuart','McDonald','Campbell','4393','Male','Yes','Yes',NULL),
('E14001190','Darlington','North East','England','County','Lab gain from Con','Con','Conservative','Peter','Gibson','Alexander','4754','Male','Yes','Yes',NULL),
('E14001191','Dartford','South East','England','County','Lab gain from Con','Con','Conservative','Gareth','Johnson','Alan','3970','Male','Yes','Yes',NULL),
('E14001193','Derby North','East Midlands','England','Borough','Lab gain from Con','Con','Conservative','Amanda','Solloway',NULL,'4372','Female','Yes','Yes',NULL),
('E14001195','Derbyshire Dales','East Midlands','England','County','Lab gain from Con','Con','Conservative','Sarah','Dines',NULL,'4816','Female','Yes','Yes',NULL),
('E14001197','Didcot and Wantage','South East','England','County','LD gain from Con','Con','Conservative','David','Johnston','Mervyn','4761','Male','Yes','Yes',NULL),
('E14001199','Doncaster East and the Isle of Axholme','Yorkshire and The Humber','England','County','Lab gain from Con','Con','Conservative','Nick','Fletcher',NULL,'4832','Male','Yes','Yes',NULL),
('E14001204','Dudley','West Midlands','England','Borough','Lab gain from Con','Con','Conservative','Marco','Longhi','Andrea','4789','Male','Yes','Yes',NULL),
('E14001206','Dunstable and Leighton Buzzard','East of England','England','County','Lab gain from Con','Con','Conservative','Andrew','Selous','Edmund Armstrong','1453','Male','Yes','Yes',NULL),
('E14001219','Eastbourne','South East','England','Borough','LD gain from Con','Con','Conservative','Caroline','Ansell',NULL,'4512','Female','Yes','Yes',NULL),
('S14000021','East Renfrewshire','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Kirsten','Oswald','Frances','4413','Female','Yes','Yes',NULL),
('S14000078','Edinburgh East and Musselburgh','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Tommy','Sheppard',NULL,'4453','Male','Yes','Yes',NULL),
('S14000079','Edinburgh North and Leith','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Deidre','Brock',NULL,'4417','Female','Yes','Yes',NULL),
('S14000081','Edinburgh South West','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Joanna','Cherry',NULL,'4419','Female','Yes','Yes',NULL),
('E14001224','Ely and East Cambridgeshire','East of England','England','County','LD gain from Con','Con','Conservative','Lucy','Frazer',NULL,'4517','Female','Yes','Yes',NULL),
('E14001228','Erewash','East Midlands','England','County','Lab gain from Con','Con','Conservative','Maggie','Throup',NULL,'4447','Female','Yes','Yes',NULL),
('E14001237','Filton and Bradley Stoke','South West','England','Borough','Lab gain from Con','Con','Conservative','Jack','Lopresti',NULL,'3989','Male','Yes','Yes',NULL),
('E14001239','Folkestone and Hythe','South East','England','County','Lab gain from Con','Con','Conservative','Damian','Collins','Noel Thomas','3986','Male','Yes','Yes',NULL),
('E14001240','Forest of Dean','South West','England','County','Lab gain from Con','Con','Conservative','Mark','Harper','James','1520','Male','Yes','Yes',NULL),
('E14001245','Gedling','East Midlands','England','County','Lab gain from Con','Con','Conservative','Tom','Randall',NULL,'4845','Male','Yes','Yes',NULL),
('E14001246','Gillingham and Rainham','South East','England','Borough','Lab gain from Con','Con','Conservative','Rehman','Chishti',NULL,'3987','Male','Yes','Yes',NULL),
('S14000084','Glasgow East','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','David','Linden',NULL,'4640','Male','Yes','Yes',NULL),
('S14000085','Glasgow North','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Alison','Thewliss','Emily','4430','Female','Yes','Yes',NULL),
('S14000086','Glasgow North East','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Anne','McLaughlin',NULL,'4437','Female','Yes','Yes',NULL),
('S14000087','Glasgow South','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Stewart','McDonald',NULL,'4461','Male','Yes','Yes',NULL),
('S14000088','Glasgow South West','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Chris','Stephens',NULL,'4463','Male','Yes','Yes',NULL),
('S14000089','Glasgow West','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Carol','Monaghan',NULL,'4443','Female','Yes','Yes',NULL),
('E14001248','Gloucester','South West','England','Borough','Lab gain from Con','Con','Conservative','Richard','Graham','Michael John Ogilvie','3990','Male','Yes','Yes',NULL),
('S14000091','Gordon and Buchan','Scotland','Scotland','County','Con hold','SNP','Scottish National Party','Richard','Thomson','Gordon','4796','Male','Yes','Yes',NULL),
('E14001254','Gravesham','South East','England','County','Lab gain from Con','Con','Conservative','Adam','Holloway','James Harold','1522','Male','Yes','Yes',NULL),
('E14001255','Great Grimsby and Cleethorpes','Yorkshire and The Humber','England','Borough','Lab gain from Con','Con','Conservative','Lia','Nici',NULL,'4851','Female','Yes','Yes',NULL),
('E14001258','Guildford','South East','England','County','LD gain from Con','Con','Conservative','Angela','Richardson','Joy','4840','Female','Yes','Yes',NULL),
('E14001261','Halesowen','West Midlands','England','Borough','Lab gain from Con','Con','Conservative','James','Morris','George','3992','Male','Yes','Yes',NULL),
('E14001269','Harrogate and Knaresborough','Yorkshire and The Humber','England','County','LD gain from Con','Con','Conservative','Andrew','Jones','Hanson','3996','Male','Yes','Yes',NULL),
('E14001272','Hartlepool','North East','England','County','Lab hold','Con','Conservative','Jill','Mortimer',NULL,'4916','Female','Yes','Yes',NULL),
('E14001274','Hastings and Rye','South East','England','County','Lab gain from Con','Con','Conservative','Sally-Ann','Hart',NULL,'4842','Female','Yes','Yes',NULL),
('E14001283','Hertford and Stortford','East of England','England','County','Lab gain from Con','Con','Conservative','Julie','Marson',NULL,'4768','Female','Yes','Yes',NULL),
('E14001285','Hexham','North East','England','County','Lab gain from Con','Con','Conservative','Guy','Opperman',NULL,'4142','Male','Yes','Yes',NULL),
('E14001287','High Peak','East Midlands','England','County','Lab gain from Con','Con','Conservative','Robert','Largan',NULL,'4852','Male','Yes','Yes',NULL),
('E14001289','Hitchin','East of England','England','County','Lab gain from Con','Con','Conservative','Bim','Afolami',NULL,'4639','Male','Yes','Yes',NULL),
('E14001291','Honiton and Sidmouth','South West','England','County','LD gain from Con','Con','Conservative','Simon','Jupp','James','4862','Male','Yes','Yes',NULL),
('E14001294','Horsham','South East','England','County','LD gain from Con','Con','Conservative','Jeremy','Quin','Mark','4507','Male','Yes','Yes','Sir'),
('E14001299','Hyndburn','North West','England','County','Lab gain from Con','Con','Conservative','Sara','Britcliffe','Alice','4838','Female','Yes','Yes',NULL),
('S14000093','Inverclyde and Renfrewshire West','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Ronnie','Cowan',NULL,'4465','Male','Yes','Yes',NULL),
('S14000094','Inverness, Skye and West Ross-shire','Scotland','Scotland','County','LD gain from SNP','SNP','Scottish National Party','Drew','Hendry',NULL,'4467','Male','Yes','Yes',NULL),
('E14001302','Ipswich','East of England','England','Borough','Lab gain from Con','Con','Conservative','Thomas','Hunt','Patrick','4771','Male','Yes','Yes',NULL),
('E14001304','Isle of Wight West','South East','England','County','Lab gain from Con','Con','Conservative','Bob','Seely','William Henry','4681','Male','Yes','Yes',NULL),
('E14001310','Kensington and Bayswater','London','England','Borough','Lab hold','Con','Conservative','Felicity','Buchan',NULL,'4821','Female','Yes','Yes',NULL),
('E14001311','Kettering','East Midlands','England','County','Lab gain from Con','Con','Conservative','Philip','Hollobone','Thomas','1537','Male','Yes','Yes',NULL),
('S14000110','Kilmarnock and Loudoun','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Alan','Brown',NULL,'4470','Male','Yes','Yes',NULL),
('E14001324','Leeds South West and Morley','Yorkshire and The Humber','England','Borough','Lab gain from Con','Con','Conservative','Andrea','Jenkyns','Marie','4490','Female','Yes','Yes','Dame'),
('E14001326','Leicester East','East Midlands','England','Borough','Con gain from Lab','Ind','Independent','Claudia','Webbe','Naomi','4848','Female','Yes','Yes',NULL),
('E14001327','Leicester South','East Midlands','England','Borough','Ind gain from Lab','Lab','Labour','Jonathan','Ashworth','Michael Graham','4244','Male','Yes','Yes',NULL),
('E14001330','Lewes','South East','England','County','LD gain from Con','Con','Conservative','Maria','Caulfield','Colette','4492','Female','Yes','Yes',NULL),
('E14001335','Lichfield','West Midlands','England','County','Lab gain from Con','Con','Conservative','Michael','Fabricant','Louis David','280','Male','Yes','Yes','Sir'),
('E14001336','Lincoln','East Midlands','England','Borough','Lab gain from Con','Con','Conservative','Karl','McCartney','Ian','4028','Male','Yes','Yes',NULL),
('S14000095','Livingston','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Hannah','Bardell','Mary','4486','Female','Yes','Yes',NULL),
('E14001342','Loughborough','East Midlands','England','County','Lab gain from Con','Con','Conservative','Jane','Hunt','Marion','4839','Female','Yes','Yes',NULL),
('E14001344','Lowestoft','East of England','England','County','Lab gain from Con','Con','Conservative','Peter','Aldous','James Guy','4069','Male','Yes','Yes',NULL),
('E14001347','Macclesfield','North West','England','County','Lab gain from Con','Con','Conservative','David','Rutley','Henry','4033','Male','Yes','Yes',NULL),
('E14001355','Mansfield','East Midlands','England','County','Lab gain from Con','Con','Conservative','Ben','Bradley','David','4663','Male','Yes','Yes',NULL),
('E14001356','Melksham and Devizes','South West','England','County','LD gain from Con','Con','Conservative','Michelle','Donelan','Emma May Elizabeth','4530','Female','Yes','Yes',NULL),
('W07000100','Mid and South Pembrokeshire','Wales','Wales','County','Lab gain from Con','Con','Conservative','Stephen','Crabb',NULL,'1554','Male','Yes','Yes',NULL),
('E14001368','Middlesbrough South and East Cleveland','North East','England','County','Lab gain from Con','Con','Conservative','Simon','Clarke','Richard','4655','Male','Yes','Yes','Sir '),
('E14001363','Mid Dorset and North Poole','South West','England','County','LD gain from Con','Con','Conservative','Michael','Tomlinson','James','4497','Male','Yes','Yes',NULL),
('S14000097','Mid Dunbartonshire','Scotland','Scotland','County','LD gain from SNP','SNP','Scottish National Party','Amy','Callaghan',NULL,'4770','Female','Yes','Yes',NULL),
('S14000045','Midlothian','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Owen','Thompson','George','4482','Male','Yes','Yes',NULL),
('E14001370','Milton Keynes North','South East','England','County','Lab gain from Con','Con','Conservative','Ben','Everitt','William','4836','Male','Yes','Yes',NULL),
('W07000101','Monmouthshire','Wales','Wales','County','Lab gain from Con','Con','Conservative','David','Davies','Thomas Charles','1545','Male','Yes','Yes',NULL),
('W07000102','Montgomeryshire and Glyndwr','Wales','Wales','County','Lab gain from Con','Con','Conservative','Craig','Williams',NULL,'4438','Male','Yes','Yes',NULL),
('E14001372','Morecambe and Lunesdale','North West','England','County','Lab gain from Con','Con','Conservative','David','Morris','Thomas','4135','Male','Yes','Yes',NULL),
('S14000099','Motherwell, Wishaw and Carluke','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Marion','Fellows',NULL,'4440','Female','Yes','Yes',NULL),
('S14000027','Na h-Eileanan an Iar','Scotland','Scotland','County','Lab gain from SNP','Ind','Independent','Angus','MacNeil','Brendan','1546','Male','Yes','Yes',NULL),
('E14001376','Newbury','South East','England','County','LD gain from Con','Con','Conservative','Laura','Farris','Rose','4826','Female','Yes','Yes',NULL),
('E14001381','Newton Abbot','South West','England','County','LD gain from Con','Con','Conservative','Anne Marie','Morris',NULL,'4249','Female','Yes','Yes',NULL),
('E14001382','Newton Aycliffe and Spennymoor','North East','England','County','Lab gain from Con','Con','Conservative','Paul','Howell',NULL,'4830','Male','Yes','Yes',NULL),
('E14001407','Northampton South','East Midlands','England','Borough','Lab gain from Con','Con','Conservative','Andrew','Lewer','Iain','4659','Male','Yes','Yes',NULL),
('N05000012','North Antrim','Northern Ireland','Northern Ireland','County','TUV gain from DUP','DUP','Democratic Unionist Party','Ian','Paisley','Richard Kyle','4129','Male','Yes','Yes',NULL),
('S14000048','North Ayrshire and Arran','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Patricia','Gibson',NULL,'4435','Female','Yes','Yes',NULL),
('E14001385','North Cornwall','South West','England','County','LD gain from Con','Con','Conservative','Scott','Mann','Leslie','4496','Male','Yes','Yes',NULL),
('E14001387','North Devon','South West','England','County','LD gain from Con','Con','Conservative','Selaine','Saxby','Rachel','4863','Female','Yes','Yes',NULL),
('N05000013','North Down','Northern Ireland','Northern Ireland','County','Ind gain from Alliance','Alliance','Alliance','Stephen','Farry','Anthony','4856','Male','Yes','Yes',NULL),
('E14001391','North East Derbyshire','East Midlands','England','County','Lab gain from Con','Con','Conservative','Lee','Rowley','Benjamin','4652','Male','Yes','Yes',NULL),
('E14001392','North East Hampshire','South East','England','County','LD gain from Con','Con','Conservative','Ranil','Jayawardena','Malcolm','4498','Male','Yes','Yes',NULL),
('E14001394','North East Somerset and Hanham','South West','England','County','Lab gain from Con','Con','Conservative','Jacob','Rees-Mogg','William','4099','Male','Yes','Yes','Sir'),
('E14001395','North Herefordshire','West Midlands','England','County','Green gain from Con','Con','Conservative','Bill','Wiggin','David','1428','Male','Yes','Yes','Sir'),
('E14001396','North Norfolk','East of England','England','County','LD gain from Con','Con','Conservative','Duncan','Baker','Charles ','4784','Male','Yes','Yes',NULL),
('E14001397','North Northumberland','North East','England','County','Lab gain from Con','Con','Conservative','Anne-Marie','Trevelyan',NULL,'4531','Female','Yes','Yes',NULL),
('E14001398','North Shropshire','West Midlands','England','County','LD gain from Con','Con','Conservative','Simon','Baynes','Robert Maurice','4800','Male','Yes','Yes',NULL),
('E14001399','North Somerset','South West','England','County','Lab gain from Con','Con','Conservative','Liam','Fox',NULL,'223','Male','Yes','Yes','Sir'),
('E14001400','North Warwickshire and Bedworth','West Midlands','England','County','Lab gain from Con','Con','Conservative','Craig','Tracey','Paul','4509','Male','Yes','Yes',NULL),
('E14001401','North West Cambridgeshire','East of England','England','County','Lab gain from Con','Con','Conservative','Shailesh','Vara','Lakhman','1496','Male','Yes','Yes',NULL),
('E14001404','North West Leicestershire','East Midlands','England','County','Lab gain from Con','Ind','Independent','Andrew','Bridgen','James','4133','Male','Yes','Yes',NULL),
('E14001413','Nuneaton','West Midlands','England','County','Lab gain from Con','Con','Conservative','Marcus','Jones','Charles','4024','Male','Yes','Yes',NULL),
('E14001418','Ossett and Denby Dale','Yorkshire and The Humber','England','County','Lab gain from Con','Con','Conservative','Mark','Eastwood','Simon','4807','Male','Yes','Yes',NULL),
('S14000101','Paisley and Renfrewshire North','Scotland','Scotland','Borough','Lab gain from SNP','SNP','Scottish National Party','Gavin','Newlands','Andrew Stuart','4420','Male','Yes','Yes',NULL),
('E14001422','Pendle and Clitheroe','North West','England','County','Lab gain from Con','Con','Conservative','Andrew','Stephenson','George','4044','Male','Yes','Yes',NULL),
('E14001423','Penistone and Stocksbridge','Yorkshire and The Humber','England','County','Lab gain from Con','Con','Conservative','Miriam','Cates','Joy','4865','Female','Yes','Yes',NULL),
('E14001424','Penrith and Solway','North West','England','County','Lab gain from Con','Con','Conservative','Mark','Jenkinson','Ian','4752','Male','Yes','Yes',NULL),
('E14001425','Peterborough','East of England','England','County','Lab gain from Con','Con','Conservative','Paul','Bristow',NULL,'4792','Male','Yes','Yes',NULL),
('E14001426','Plymouth Moor View','South West','England','Borough','Lab gain from Con','Con','Conservative','Johnny','Mercer','Luther','4485','Male','Yes','Yes',NULL),
('E14001429','Poole','South West','England','Borough','Lab gain from Con','Con','Conservative','Robert','Syms','Andrew Raymond','245','Male','Yes','Yes','Sir'),
('E14001431','Portsmouth North','South East','England','Borough','Lab gain from Con','Con','Conservative','Penny','Mordaunt',NULL,'4017','Female','Yes','Yes',NULL),
('E14001440','Redcar','North East','England','Borough','Lab gain from Con','Con','Conservative','Jacob','Young',NULL,'4825','Male','Yes','Yes',NULL),
('E14001441','Redditch','West Midlands','England','County','Lab gain from Con','Con','Conservative','Rachel','Maclean','Helen','4668','Female','Yes','Yes',NULL),
('E14001443','Ribble Valley','North West','England','County','Lab gain from Con','Con','Conservative','Nigel','Evans','Martin','474','Male','Yes','Yes',NULL),
('E14001446','Rochdale','North West','England','County','Lab hold','WPB','Workers Party of Britain','George','Galloway',NULL,'609','Male','Yes','Yes',NULL),
('E14001447','Rochester and Strood','South East','England','County','Lab gain from Con','Con','Conservative','Kelly','Tolhurst','Jane','4487','Female','Yes','Yes',NULL),
('E14001450','Rossendale and Darwen','North West','England','County','Lab gain from Con','Con','Conservative','Jake','Berry',NULL,'4060','Male','Yes','Yes','Sir'),
('E14001451','Rother Valley','Yorkshire and The Humber','England','County','Lab gain from Con','Con','Conservative','Alexander','Stafford',NULL,'4866','Male','Yes','Yes',NULL),
('E14001457','Rushcliffe','East Midlands','England','County','Lab gain from Con','Con','Conservative','Ruth','Edwards','Rosamond','4808','Female','Yes','Yes',NULL),
('E14001462','Scunthorpe','Yorkshire and The Humber','England','County','Lab gain from Con','Con','Conservative','Holly','Mumby-Croft',NULL,'4867','Female','Yes','Yes',NULL),
('E14001471','Sherwood Forest','East Midlands','England','County','Lab gain from Con','Con','Conservative','Mark','Spencer','Steven','4055','Male','Yes','Yes','Sir'),
('E14001472','Shipley','Yorkshire and The Humber','England','County','Lab gain from Con','Con','Conservative','Philip','Davies',NULL,'1565','Male','Yes','Yes','Sir'),
('E14001473','Shrewsbury','West Midlands','England','County','Lab gain from Con','Con','Conservative','Daniel','Kawczynski','Robert','1566','Male','Yes','Yes',NULL),
('E14001479','Solihull West and Shirley','West Midlands','England','Borough','Con hold','Ind','Independent','Julian','Knight','Carlton','4410','Male','Yes','Yes',NULL),
('N05000014','South Antrim','Northern Ireland','Northern Ireland','County','UUP gain from DUP','DUP','Democratic Unionist Party','Paul','Girvan',NULL,'4633','Male','Yes','Yes',NULL),
('E14001480','South Basildon and East Thurrock','East of England','England','County','RUK gain from Con','Con','Conservative','Stephen','Metcalfe','James','4092','Male','Yes','Yes',NULL),
('E14001482','South Cotswolds','South West','England','County','LD gain from Con','Con','Conservative','James','Gray','Whiteside','261','Male','Yes','Yes',NULL),
('E14001483','South Derbyshire','East Midlands','England','County','Lab gain from Con','Con','Conservative','Heather','Wheeler','Kay','4053','Female','Yes','Yes',NULL),
('E14001484','South Devon','South West','England','County','LD gain from Con','Con','Conservative','Anthony','Mangnall','James Holland','4762','Male','Yes','Yes',NULL),
('E14001485','South Dorset','South West','England','County','Lab gain from Con','Con','Conservative','Richard','Drax','Grosvenor Plunkett-Ernle-Erle','4132','Male','Yes','Yes',NULL),
('E14001486','South East Cornwall','South West','England','County','Lab gain from Con','Con','Conservative','Sheryll','Murray',NULL,'4100','Female','Yes','Yes','Mrs'),
('E14001502','Southend West and Leigh','East of England','England','Borough','Lab gain from Con','Con','Conservative','Anna','Firth',NULL,'4936','Female','Yes','Yes',NULL),
('E14001504','Southport','North West','England','County','Lab gain from Con','Con','Conservative','Damien','Moore',NULL,'4669','Male','Yes','Yes',NULL),
('E14001491','South Ribble','North West','England','County','Lab gain from Con','Con','Conservative','Katherine','Fletcher',NULL,'4834','Female','Yes','Yes',NULL),
('E14001497','South West Norfolk','East of England','England','County','Lab gain from Con','Con','Conservative','Liz','Truss',NULL,'4097','Female','Yes','Yes',NULL),
('E14001513','Stafford','West Midlands','England','County','Lab gain from Con','Con','Conservative','Theo','Clarke',NULL,'4819','Female','Yes','Yes',NULL),
('E14001508','St Austell and Newquay','South West','England','County','Lab gain from Con','Con','Conservative','Steve','Double','Daniel','4452','Male','Yes','Yes',NULL),
('S14000105','Stirling and Strathallan','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Alyn','Smith',NULL,'4738','Male','Yes','Yes',NULL),
('E14001511','St Ives','South West','England','County','LD gain from Con','Con','Conservative','Derek','Thomas','Gordon','4532','Male','Yes','Yes',NULL),
('E14001512','St Neots and Mid Cambridgeshire','East of England','England','County','LD gain from Con','Con','Conservative','Anthony','Browne','Howe','4801','Male','Yes','Yes',NULL),
('E14001521','Stoke-on-Trent North','West Midlands','England','Borough','Lab gain from Con','Con','Conservative','Jonathan','Gullis','Edward','4814','Male','Yes','Yes',NULL),
('E14001522','Stoke-on-Trent South','West Midlands','England','County','Lab gain from Con','Con','Conservative','Jack','Brereton',NULL,'4643','Male','Yes','Yes',NULL),
('E14001524','Stourbridge','West Midlands','England','Borough','Lab gain from Con','Con','Conservative','Suzanne','Webb',NULL,'4802','Female','Yes','Yes',NULL),
('E14001526','Stratford-on-Avon','West Midlands','England','County','LD gain from Con','Con','Conservative','Chris','Clarkson',NULL,'4835','Male','Yes','Yes',NULL),
('E14001529','Stroud','South West','England','County','Lab gain from Con','Con','Conservative','Siobhan','Baillie','Kathleen','4847','Female','Yes','Yes',NULL),
('E14001530','Suffolk Coastal','East of England','England','County','Lab gain from Con','Con','Conservative','Thérèse','Coffey','Anne','4098','Female','Yes','Yes','Dr'),
('E14001536','Swindon North','South West','England','County','Lab gain from Con','Con','Conservative','Justin','Tomlinson','Paul','4105','Male','Yes','Yes',NULL),
('E14001537','Swindon South','South West','England','Borough','Lab gain from Con','Con','Conservative','Robert','Buckland','James','4106','Male','Yes','Yes','Sir'),
('E14001538','Tamworth','West Midlands','England','County','Lab gain from Con','Con','Conservative','Eddie','Hughes','Francis','4635','Male','Yes','Yes',NULL),
('E14001540','Taunton and Wellington','South West','England','County','LD gain from Con','Con','Conservative','Rebecca','Pow','Faye','4522','Female','Yes','Yes',NULL),
('E14001542','Tewkesbury','South West','England','County','LD gain from Con','Con','Conservative','Laurence','Robertson','Anthony','253','Male','Yes','Yes','Mr'),
('E14001545','Thornbury and Yate','South West','England','County','LD gain from Con','Con','Conservative','Luke','Hall','Anthony','4450','Male','Yes','Yes',NULL),
('E14001546','Thurrock','East of England','England','Borough','Lab gain from Con','Con','Conservative','Jacqueline','Doyle-Price',NULL,'4065','Female','Yes','Yes','Dame'),
('E14001547','Tipton and Wednesbury','West Midlands','England','Borough','Lab gain from Con','Con','Conservative','Shaun','Bailey','Stephen','4757','Male','Yes','Yes',NULL),
('E14001548','Tiverton and Minehead','South West','England','County','LD gain from Con','Con','Conservative','Ian','Liddell-Grainger','Richard Peregrine','1396','Male','Yes','Yes','Mr'),
('E14001551','Torbay','South West','England','Borough','LD gain from Con','Con','Conservative','Kevin','Foster','John','4451','Male','Yes','Yes',NULL),
('E14001554','Truro and Falmouth','South West','England','County','Lab gain from Con','Con','Conservative','Cherilyn','Mackrory',NULL,'4758','Female','Yes','Yes',NULL),
('E14001558','Uxbridge and South Ruislip','London','England','Borough','Lab gain from Con','Con','Conservative','Steve','Tuckwell',NULL,'4994','Male','Yes','Yes',NULL),
('W07000110','Vale of Glamorgan','Wales','Wales','County','Lab gain from Con','Con','Conservative','Alun','Cairns','Hugh','4086','Male','Yes','Yes',NULL),
('E14001565','Warrington South','North West','England','County','Lab hold','Con','Conservative','Andy','Carter',NULL,'4791','Male','Yes','Yes',NULL),
('E14001568','Watford','East of England','England','Borough','Lab gain from Con','Con','Conservative','Dean','Russell',NULL,'4812','Male','Yes','Yes',NULL),
('E14001573','Welwyn Hatfield','East of England','England','County','Lab gain from Con','Con','Conservative','Grant','Shapps',NULL,'1582','Male','Yes','Yes',NULL),
('E14001575','West Dorset','South West','England','County','LD gain from Con','Con','Conservative','Chris','Loder',NULL,'4751','Male','Yes','Yes',NULL),
('S14000106','West Dunbartonshire','Scotland','Scotland','County','Lab gain from SNP','SNP','Scottish National Party','Martin','Docherty-Hughes',NULL,'4374','Male','Yes','Yes',NULL),
('E14001581','Weston-super-Mare','South West','England','County','Lab gain from Con','Con','Conservative','John','Penrose','David','1584','Male','Yes','Yes',NULL),
('E14001587','Winchester','South East','England','County','LD gain from Con','Con','Conservative','Flick','Drummond',NULL,'4459','Female','Yes','Yes','Mrs'),
('E14001591','Witney','South East','England','County','LD gain from Con','Con','Conservative','Robert','Courts','Alexander','4589','Male','Yes','Yes',NULL),
('E14001592','Woking','South East','England','Borough','LD gain from Con','Con','Conservative','Jonathan','Lord','George Caladine','4090','Male','Yes','Yes',NULL),
('E14001594','Wolverhampton North East','West Midlands','England','Borough','Lab gain from Con','Con','Conservative','Jane','Stevenson','Fiona Catherine','4750','Female','Yes','Yes',NULL),
('E14001599','Worthing West','South East','England','County','Lab gain from Con','Con','Conservative','Peter','Bottomley','James','117','Male','Yes','Yes','Sir'),
('W07000111','Wrexham','Wales','Wales','County','Lab gain from Con','Con','Conservative','Sarah','Atherton','Elizabeth','4855','Female','Yes','Yes',NULL),
('E14001600','Wycombe','South East','England','County','Lab gain from Con','Con','Conservative','Steve','Baker',NULL,'4064','Male','Yes','Yes',NULL),
('E14001603','Yeovil','South West','England','County','LD gain from Con','Con','Conservative','Marcus','Fysh','John Hudson','4446','Male','Yes','Yes','Mr'),
('W07000112','Ynys MÃ´n','Wales','Wales','County','PC gain from Con','Con','Conservative','Virginia','Crosbie','Ann','4859','Female','Yes','Yes',NULL),
('E14001605','York Outer','Yorkshire and The Humber','England','County','Lab gain from Con','Con','Conservative','Julian','Sturdy','Charles','4079','Male','Yes','Yes',NULL);
